sudo: false
dist: trusty
language: python
python:
  - "2.7.13"
  - "3.6.1"
before_install:
  - pip install pycodestyle
  - pycodestyle --ignore=E501,E712,E722,W503 Adversary/*.py
install:
  - pip install pandas
  - pip install textblob
script: py.test -s